version: 2

python:
  install:
    - requirements: docs/requirements-rtd.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

conda:
  environment: ci/environment-docs.yml
