name: xmovie-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  # Core
  - xarray
  - matplotlib
  - cartopy
  - ffmpeg
  # Optional
  - tqdm
  - dask-core
  # Examples
  - pooch
  - jupyterlab
  - ipywidgets
  # Docs
  - sphinx
  - sphinx-autobuild
  - sphinx-book-theme
  - nbsphinx
  #
  - pip
  - pip:
    - '-e ../'  # xmovie
