# Conda environment for testing xmovie in CI
name: xmovie-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  #
  # xmovie core
  - dask-core
  - matplotlib
  - numpy
  - xarray
  #
  - ffmpeg
  #
  # Extras
  - cartopy
  # - cftime
  # - nc-time-axis
  # - scipy
  # - tqdm
  #
  # Test
  - opencv
  - pillow
  - pytest
  - pytest-cov
