# Conda environment for docs development,
# including running the example notebooks
name: xmovie-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  #
  # xmovie core
  - matplotlib
  - numpy
  - xarray
  #
  - ffmpeg
  #
  # Optional
  - cartopy
  - dask-core
  - tqdm
  #
  # Example notebooks
  - ipywidgets
  - jupyterlab
  - pooch
  #
  # Docs
  - nbsphinx
  - sphinx>=4.0
  - sphinx-autobuild
  - sphinx-book-theme
  - sphinx-copybutton
  #
  - pip:
    - sphinx-prompt
    - '-e ../'  # xmovie itself
